baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Bella Fishman's Resume"
theme = 'cactus'


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/bellafishman"
[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/isabella-fishman/"
